config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users
  resources :contacts
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true
  validates :phone, presence: true, length: { maximum: 12 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :contacts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: %i[show edit update destroy]

  def index
    @contacts = current_user.contacts.all
  end

  def new
    @contact = current_user.contacts.new
  end

  def edit; end

  def create
    @contact = current_user.contacts.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Contato criado com sucesso.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: 'Contato atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_path, notice: 'Contato apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :address)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= contact.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= contact.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= contact.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= contact.address %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this contact", contact, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this contact', edit_contact_path(contact), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, class: "contents") do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <div class="flex p-4 mb-4 text-sm text-center text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800">
        <svg class="inline flex-shrink-0 mr-3 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
        <ul>
          <% contact.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="max-w-2xl mx-auto bg-white p-16 rounded-lg my-10">
    <h1 class="font-bold text-4xl text-center">Novo Contato</h1>
    <div class="grid gap-6 mb-6 lg:grid-cols-2">
      <div class="my-5">
        <%= form.label :name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
        <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>

      <div class="my-5">
        <%= form.label :phone, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
        <%= form.text_field :phone, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>
    </div>

    <div class="my-5">
      <%= form.label :email, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
      <%= form.text_field :email, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>

    <div class="my-5">
      <%= form.label :address, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
      <%= form.text_field :address, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>

    <div class="inline">
      <%= form.submit "Cadastrar", class: "rounded-lg py-3 px-5 bg-gradient-to-r from-indigo-400 via-indigo-500 to-indigo-400 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 text-white inline-block font-bold cursor-pointer my-5" %>
      <%= link_to 'Voltar', contacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gradient-to-r from-indigo-400 via-indigo-500 to-indigo-400 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 inline-block font-bold text-white" %>
    </div>
    </div>
  </div>
<% end %>

app/views/contacts/_form1.html.erb
<%= form_with(model: contact, class: "contents") do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="max-w-2xl mx-auto bg-white p-16 rounded-lg my-10">
    <h1 class="font-bold text-4xl text-center">Editar Contato</h1>
    <div class="grid gap-6 mb-6 lg:grid-cols-2">
      <div class="my-5">
        <%= form.label :name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
        <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>

      <div class="my-5">
        <%= form.label :phone, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
        <%= form.text_field :phone, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>
    </div>

    <div class="my-5">
      <%= form.label :email, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
      <%= form.text_field :email, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>

    <div class="my-5">
      <%= form.label :address, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
      <%= form.text_field :address, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>

    <div class="inline">
      <%= form.submit "Editar", class: "rounded-lg py-3 px-5 bg-gradient-to-r from-indigo-400 via-indigo-500 to-indigo-400 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 text-white inline-block font-bold cursor-pointer my-5" %>
      <%= link_to 'Voltar', contacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gradient-to-r from-indigo-400 via-indigo-500 to-indigo-400 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 inline-block font-bold text-white" %>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form1", contact: @contact %>

</div>

app/views/contacts/index.html.erb
<div class="relative overflow-x-auto shadow-md sm:rounded-lg my-10">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <h1 class="text-white font-bold text-4xl my-6">Contatos</h1>
    <thead class="text-center text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">
          NOME
        </th>
        <th scope="col" class="px-6 py-3">
          TELEFONE
        </th>
        <th scope="col" class="px-6 py-3">
          EMAIL
        </th>
        <th scope="col" class="px-6 py-3">
          ENDEREÇO
        </th>
        <th scope="col" class="px-6 py-3">
            <span class="sr-only">Editar</span>
        </th>
        <th scope="col" class="px-6 py-3">
          <%= link_to 'Novo Contato', new_contact_path, class: "text-center rounded-lg py-3 px-5 bg-gradient-to-r from-indigo-400 via-indigo-500 to-indigo-400 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 text-white block font-medium" %>
        </th>
      </tr>
    </thead>
    <tbody class="bg-white text-center">
      <% @contacts.each do |contact| %>
        <tr class="border-b dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700">
          <th scope="row" class="px-6 py-4">
            <%= contact.name %>
          </th>
          <td scope="row" class="px-6 py-4">
            <%= contact.phone %>
          </td>
          <td class="px-6 py-4">
            <%= contact.email %>
          </td>
          <td class="px-6 py-4">
            <%= contact.address %>
          </td>
          <td class="px-6 py-4 text-right">
              <%= link_to 'Editar', edit_contact_path(contact), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline"%>
          </td>
          <td class="px-6 py-4 text-right">
            <%= link_to 'Apagar', contact, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline", method: :delete, data: { confirm: 'Tem certeza em apagar?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", contact: @contact %>

</div>

app/views/home/index.html.erb
<div class="relative overflow-hidden bg-no-repeat bg-cover" style="
  background-position: 100%;
  height: 550px;
">
  <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed">
    <div class="flex justify-center items-center h-full">
      <div class="text-center text-white px-6 md:px-12">
        <h1 class="text-5xl font-bold mt-0 mb-6">Bem vindo a sua Agenda Virtual</h1>
        <h6 class="text-xl mb-8">Gerencie sua agenda de contatos em qualquer lugar</h6>
        <a href="/users/sign_up" class="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-bold rounded-lg text-lg px-8 py-2.5 text-center mr-2 mb-2">Inscrever-se</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-gray-200 text-center lg:text-left">
  <div class="text-gray-700 text-center p-4" style="background-color: rgba(0, 0, 0, 0.2);">
    <p>&copy; <%= Time.current.year %> Agenda Virtual
      <a class="text-gray-800" href="https://www.linkedin.com/in/betomachado3">Criado por Beto Machado</a>
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="bg-gray-200 border-gray-200 px-2 sm:px-4 py-2.5 dark:bg-gray-800">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
      <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
        <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
          <% if user_signed_in? %>
            <li>
              <a href="/" class="block py-2 pr-4 pl-3 text-gray-700 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" aria-current="page">Home</a>
            </li>
            <li>
              <%= link_to 'Meus Contatos', contacts_path, class: "block py-2 pr-4 pl-3 text-gray-700 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
            </li>
            <li>
              <%= link_to 'Editar perfil', edit_user_registration_path, class: "block py-2 pr-4 pl-3 text-gray-700 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
            </li>
            <li>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "w-full text-white bg-gradient-to-r from-indigo-400 via-indigo-500 to-indigo-400 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-bold rounded-lg py-2 px-4 mb-6" %>
            </li>
          <% else %>
            <li>
              <a href="/" class="block py-2 pr-4 pl-3 text-gray-700 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" aria-current="page">Home</a>
            </li>
            <li>
              <%= link_to 'Meus Contatos', contacts_path, class: "block py-2 pr-4 pl-3 text-gray-700 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
            </li>
            <li>
              <%= link_to "Inscrever-se", new_user_registration_path, class: "w-full text-white bg-gradient-to-r from-indigo-400 via-indigo-500 to-indigo-400 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-bold rounded-lg py-2 px-4 mb-6" %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path, class: "w-full text-white bg-gradient-to-r from-indigo-400 via-indigo-500 to-indigo-400 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-bold rounded-lg py-2 px-4 mb-6" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda Virtual</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="image">

    <%= render 'layouts/header' %>

    <% if notice %>
      <p class="flex p-4 mb-4 text-sm text-center text-green-700 bg-green-100 rounded-lg dark:bg-green-200 dark:text-green-800 text-center"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="flex p-4 mb-4 text-sm text-center text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800 "><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>